version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:

    # Use the env_file to store your personal settings
    env_file:
      - ".env"

    hostname: ${HOSTNAME}
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped

    # Pi-hole ports mapped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"

    # Pi-hole environment details
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}

    # Volumes store your data outside of the container
    volumes:
      - "./etc-pihole:/etc/pihole/"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d/"